package pie.core.engine.test.gui;

import java.util.concurrent.TimeUnit;
import pie.core.engine.EngineFactory;
import pie.core.engine.IEngine;
import pie.core.engine.security.SimpleConfiguration;
import pie.core.engine.security.UserCredential;
import pie.core.engine.util.PieLogger;
import pie.core.engine.worker.COMMAND;
import pie.core.engine.worker.CommandWorker;
import pie.core.engine.worker.IWorkListener;
import pie.core.engine.worker.IWorker;



/**
 *
 * @author Saiful.I Raju
 * @email saiful.raju@gmail.com
 * 
 */
public class MainUI extends javax.swing.JFrame  implements IWorkListener{

   private  SimpleEmailWorker simpleEmailWorker = null;
   private SimpleSMSWorker simpleSMSWorker  = null;
   private CommandWorker emailCommandWorker = null;
   private CommandWorker smsCommandWorker = null;
    /**
     * Creates new form MainUI
     */
    public MainUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        leftPanel = new javax.swing.JPanel();
        buttonStart = new javax.swing.JButton();
        buttonStop = new javax.swing.JButton();
        rightPanel = new javax.swing.JPanel();
        topPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        right = new javax.swing.JPanel();
        smsAdapterButtonStop = new javax.swing.JButton();
        smsAdapterButtonStart = new javax.swing.JButton();
        left = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        right1 = new javax.swing.JPanel();
        emailAdapterButtonStop = new javax.swing.JButton();
        emailAdapterButtonStart = new javax.swing.JButton();
        left1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        bottomPanel = new javax.swing.JPanel();
        displayPane = new javax.swing.JScrollPane();
        displayTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        leftPanel.setBackground(new java.awt.Color(153, 255, 255));
        leftPanel.setPreferredSize(new java.awt.Dimension(120, 300));
        leftPanel.setLayout(new java.awt.GridBagLayout());

        buttonStart.setBackground(new java.awt.Color(255, 255, 255));
        buttonStart.setText("Engine Start");
        buttonStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonStartActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(131, 10, 0, 17);
        leftPanel.add(buttonStart, gridBagConstraints);

        buttonStop.setBackground(new java.awt.Color(255, 255, 255));
        buttonStop.setText("Engine Stop");
        buttonStop.setToolTipText("");
        buttonStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonStopActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 10, 174, 17);
        leftPanel.add(buttonStop, gridBagConstraints);

        jPanel1.add(leftPanel, java.awt.BorderLayout.LINE_START);

        rightPanel.setBackground(new java.awt.Color(255, 255, 255));
        rightPanel.setLayout(new java.awt.BorderLayout());

        topPanel.setBackground(new java.awt.Color(153, 153, 153));
        topPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        topPanel.setPreferredSize(new java.awt.Dimension(100, 100));
        topPanel.setLayout(new javax.swing.BoxLayout(topPanel, javax.swing.BoxLayout.X_AXIS));

        jPanel2.setLayout(new java.awt.BorderLayout());

        right.setPreferredSize(new java.awt.Dimension(200, 0));

        smsAdapterButtonStop.setBackground(new java.awt.Color(255, 255, 255));
        smsAdapterButtonStop.setText("Stop");
        smsAdapterButtonStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smsAdapterButtonStopActionPerformed(evt);
            }
        });

        smsAdapterButtonStart.setBackground(new java.awt.Color(255, 255, 255));
        smsAdapterButtonStart.setText("Start");
        smsAdapterButtonStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smsAdapterButtonStartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout rightLayout = new javax.swing.GroupLayout(right);
        right.setLayout(rightLayout);
        rightLayout.setHorizontalGroup(
            rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(smsAdapterButtonStart)
                .addGap(18, 18, 18)
                .addComponent(smsAdapterButtonStop, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        rightLayout.setVerticalGroup(
            rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rightLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(smsAdapterButtonStart)
                    .addComponent(smsAdapterButtonStop))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(right, java.awt.BorderLayout.LINE_END);

        jLabel1.setText("SMS Adapter");

        javax.swing.GroupLayout leftLayout = new javax.swing.GroupLayout(left);
        left.setLayout(leftLayout);
        leftLayout.setHorizontalGroup(
            leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        leftLayout.setVerticalGroup(
            leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(left, java.awt.BorderLayout.CENTER);

        jPanel3.setLayout(new java.awt.BorderLayout());

        right1.setPreferredSize(new java.awt.Dimension(200, 0));

        emailAdapterButtonStop.setBackground(new java.awt.Color(255, 255, 255));
        emailAdapterButtonStop.setText("Stop");
        emailAdapterButtonStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailAdapterButtonStopActionPerformed(evt);
            }
        });

        emailAdapterButtonStart.setBackground(new java.awt.Color(255, 255, 255));
        emailAdapterButtonStart.setText("Start");
        emailAdapterButtonStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailAdapterButtonStartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout right1Layout = new javax.swing.GroupLayout(right1);
        right1.setLayout(right1Layout);
        right1Layout.setHorizontalGroup(
            right1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(right1Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(emailAdapterButtonStart)
                .addGap(18, 18, 18)
                .addComponent(emailAdapterButtonStop, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        right1Layout.setVerticalGroup(
            right1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, right1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(right1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailAdapterButtonStart)
                    .addComponent(emailAdapterButtonStop))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(right1, java.awt.BorderLayout.LINE_END);

        jLabel2.setText("Email Adapter");

        javax.swing.GroupLayout left1Layout = new javax.swing.GroupLayout(left1);
        left1.setLayout(left1Layout);
        left1Layout.setHorizontalGroup(
            left1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(left1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        left1Layout.setVerticalGroup(
            left1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(left1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(left1, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        topPanel.add(jPanel2);

        rightPanel.add(topPanel, java.awt.BorderLayout.NORTH);

        bottomPanel.setPreferredSize(new java.awt.Dimension(300, 50));
        bottomPanel.setLayout(new java.awt.CardLayout());

        displayTextArea.setColumns(20);
        displayTextArea.setRows(5);
        displayTextArea.setPreferredSize(new java.awt.Dimension(100, 50));
        displayPane.setViewportView(displayTextArea);

        bottomPanel.add(displayPane, "card2");

        rightPanel.add(bottomPanel, java.awt.BorderLayout.CENTER);

        jPanel1.add(rightPanel, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonStartActionPerformed
        // TODO add your handling code here:
        IEngine engine = EngineFactory.getEngine();
        if(!engine.isRunning()){
            engine.start(new SimpleConfiguration(10, 10, new UserCredential("", ""), false));
        } else {
            PieLogger.log("Engine is running ");
        }
        
    }//GEN-LAST:event_buttonStartActionPerformed

    private void buttonStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonStopActionPerformed
        // TODO add your handling code here:
        IEngine engine = EngineFactory.getEngine();
         if(engine.isRunning()){
             EngineFactory.getEngine().stop();
         } else {
             PieLogger.log("Engine is not running ");
         }
        
    }//GEN-LAST:event_buttonStopActionPerformed

    private void emailAdapterButtonStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailAdapterButtonStopActionPerformed
        // TODO add your handling code here:
        IEngine engine = EngineFactory.getEngine();
          if (engine.isStop(SimpleEmailWorker.class)) {
            PieLogger.log("Email  adapter is not running");
            return;
        }
        engine.cancel(emailCommandWorker);
        
    }//GEN-LAST:event_emailAdapterButtonStopActionPerformed

    private void emailAdapterButtonStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailAdapterButtonStartActionPerformed
        // TODO add your handling code here:
        if (!EngineFactory.getEngine().isStop(SimpleEmailWorker.class)) {
            //engineController.showMessage("Earthquake  adapter is already started and running");
            return;
        }
        simpleEmailWorker = new SimpleEmailWorker(5, TimeUnit.SECONDS);
//        emailCommandWorker = new CommandWorker
                
                 emailCommandWorker = new CommandWorker("RF", true, simpleEmailWorker,
                COMMAND.LOAD_REALTIME);
        EngineFactory.getEngine().runWork(emailCommandWorker,this);
        
    }//GEN-LAST:event_emailAdapterButtonStartActionPerformed

    private void smsAdapterButtonStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smsAdapterButtonStartActionPerformed
        // TODO add your handling code here:
        if (!EngineFactory.getEngine().isStop(SimpleSMSWorker.class)) {
            //engineController.showMessage("Earthquake  adapter is already started and running");
            return;
        }
        simpleSMSWorker = new SimpleSMSWorker(5, TimeUnit.SECONDS);
//        emailCommandWorker = new CommandWorker
                
                 smsCommandWorker = new CommandWorker("RF", true, simpleSMSWorker,
                COMMAND.LOAD_REALTIME);
        EngineFactory.getEngine().runWork(smsCommandWorker,this);
    }//GEN-LAST:event_smsAdapterButtonStartActionPerformed

    private void smsAdapterButtonStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smsAdapterButtonStopActionPerformed
        // TODO add your handling code here:
        
         IEngine engine = EngineFactory.getEngine();
          if (engine.isStop(SimpleSMSWorker.class)) {
            PieLogger.log("SMS  adapter is not running");
            return;
        }
        engine.cancel(smsCommandWorker);
    }//GEN-LAST:event_smsAdapterButtonStopActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bottomPanel;
    private javax.swing.JButton buttonStart;
    private javax.swing.JButton buttonStop;
    private javax.swing.JScrollPane displayPane;
    private javax.swing.JTextArea displayTextArea;
    private javax.swing.JButton emailAdapterButtonStart;
    private javax.swing.JButton emailAdapterButtonStop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel left;
    private javax.swing.JPanel left1;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JPanel right;
    private javax.swing.JPanel right1;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JButton smsAdapterButtonStart;
    private javax.swing.JButton smsAdapterButtonStop;
    private javax.swing.JPanel topPanel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void finished(IWorker worker) {
         System.out.println("finished():  " + worker.getId());
    }

    @Override
    public void workerAdapterIsShutdown(IWorker worker) {
        System.out.println("workerAdapterIsShutdown():   " + worker.getId());
    }

    @Override
    public void workerAdapterIsStarted(IWorker worker) {
        System.out.println("workerAdapterIsStarted():   " + worker.getId());
    }

    @Override
    public void workIsProcessing(IWorker worker) {
        System.out.println("workIsProcessing():   " + worker.getId());
    }

    @Override
    public String getSourceName() {
      return MainUI.class.getName();
    }
}
